CREATE DATABASE PRODUTOBD;

CREATE TABLE PRODUTOBD.PRODUTO (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(100)  NOT NULL,
  DESCRICAO    VARCHAR(1000) NULL,
  PRECO_COMPRA DECIMAL(9,2)  NOT NULL,
  PRECO_VENDA  DECIMAL(9,2)  NOT NULL,
  QUANTIDADE   INT           NOT NULL DEFAULT 0,
  DISPONIVEL   BOOL          NOT NULL DEFAULT TRUE,       
  DT_CADASTRO  TIMESTAMP     NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE PRODUTOBD.CATEGORIA (
  ID   INT          NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID),
  CONSTRAINT UC_NOME UNIQUE (NOME)
);

CREATE TABLE PRODUTOBD.PRODUTO_CATEGORIA (
    ID_PRODUTO   BIGINT NOT NULL,
    ID_CATEGORIA INT    NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOBD.PRODUTO(ID),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES PRODUTOBD.CATEGORIA(ID)
);

INSERT INTO PRODUTOBD.CATEGORIA(NOME) VALUES ("PS4");
INSERT INTO PRODUTOBD.CATEGORIA(NOME) VALUES ("XBOX ONE");
INSERT INTO PRODUTOBD.CATEGORIA(NOME) VALUES ("NINTENDO SWITCH");
INSERT INTO PRODUTOBD.CATEGORIA(NOME) VALUES ("PC");
INSERT INTO PRODUTOBD.CATEGORIA(NOME) VALUES ("MOBILE");

INSERT INTO PRODUTOBD.PRODUTO (NOME,DESCRICAO,PRECO_COMPRA,PRECO_VENDA,QUANTIDADE,DISPONIVEL) VALUES ("GOW","JOGO TOP ROGERINHO",3.00,6.00,10,1);
INSERT INTO PRODUTOBD.PRODUTO_CATEGORIA (ID_PRODUTO,ID_CATEGORIA) VALUES (1,2);
SELECT * FROM PRODUTOBD.PRODUTO_CATEGORIA;
